''' PESAN MENU '''
def welcome_message():
    print("\n========== RAYYSTORE GAMES! ==========")
    print('List Menu:')
    print("1. Tampilkan Produk Game")
    print("2. Tambah Produk Game")
    print("3. Update Produk Game")
    print("4. Hapus Produk Game")
    print('5. Cari Produk Game')
    print("6. Transaksi Penjualan")
    print('7. Transaksi Pembelian')
    print("8. Laporan Penjualan Harian")
    print("9. Laporan Penjualan Mingguan")
    print("10. Laporan Penjualan Bulanan")
    print("0. Keluar")
    print('==============================')
